site_name: AWS Demystified
site_url: https://sitename.example
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/logo.png
  #features:
  #  - navigation.footer
  font:
    text: Open Sans
    code: Red Hat Mono  
  palette:
      # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep orange
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: purple
      accent: deep purple

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

  # https://jameswillett.dev/getting-started-with-material-for-mkdocs/#admonitions-aka-callouts
  # and https://squidfunk.github.io/mkdocs-material/reference/admonitions/#supported-types
  - admonition
  - pymdownx.details
  